/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import controller.HocKyCon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pham Quyen
 */
public class HocKy extends javax.swing.JFrame {
    private String[] tenDeCot={ "Học kỳ", "Mã Học Sinh", "Rèn luyện", "Khen thưởng", "Tốt nghiệp", "Năm học"};
    private ArrayList<DoiTuong.HocKy> danhsach1= new ArrayList<>();
    private DefaultTableModel model;
    /**
     * Creates new form HocKy
     */
    public HocKy() {
        initComponents();
        this.lbtaikhoan.setText(DangNhapJF.mauser);
        this.lbchucvu.setText(DangNhapJF.loaiuser);
        model= (DefaultTableModel) tblDanhSach.getModel();
        model.setColumnIdentifiers(tenDeCot);
                hienThiDanhSach("select * from hocky ");
    }
    public int hienThiDanhSach(String sql){
        danhsach1= new HocKyCon().layDanhSach1(sql);        
        model.setRowCount(0);
        for(DoiTuong.HocKy h: danhsach1){
            model.addRow(new Object[]{
               h.getHocky(),h.getMaHS(), 
                 h.getRenluyen(),h.getKhenthuong(),
                 h.getTotnghiep(), h.getNamhoc()
            }
                    );
        }
        return danhsach1.size();        
    }
    
    public void XoaText(){
        txthocky.setText("");
        txtmaHS.setText("");
        txtkhenthuong.setText("");
        txtrenluyen.setText("");
        txttotnghiep.setText("");
        txtnamhoc.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txthocky = new javax.swing.JTextField();
        txtmaHS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtrenluyen = new javax.swing.JTextField();
        txtkhenthuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttotnghiep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtnamhoc = new javax.swing.JTextField();
        lbchucvu = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbtaikhoan = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("HỌC KỲ");

        jLabel2.setText("Học kỳ");

        jLabel3.setText("Mã học sinh");

        jLabel4.setText("Rèn luyện");

        jLabel5.setText("Khen thưởng");

        jLabel6.setText("Tốt nghiệp");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Xoá");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSach);

        jLabel7.setText("Năm học");

        lbchucvu.setText("none");

        jLabel9.setText("tài khoản:");

        jLabel10.setText("chức vụ:");

        lbtaikhoan.setText("none");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbchucvu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lbtaikhoan)))
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmaHS)
                                .addComponent(txthocky, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txttotnghiep)
                            .addComponent(txtkhenthuong, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtrenluyen))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lbtaikhoan))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lbchucvu))))))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txthocky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtmaHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jButton4)
                            .addComponent(jLabel7)
                            .addComponent(txtnamhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtrenluyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtkhenthuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttotnghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //them
        String hocky=null, maHS= "", renluyen=null, khenthuong=null, totnghiep=null; 
        int namhoc=0;
        boolean ok= true;
        if("".equals(txthocky.getText())){
            JOptionPane.showMessageDialog(rootPane, "Hoc ky khong duoc de trong");
            ok= false;
        }
        else {
            hocky= txthocky.getText();
        }
        if("".equals(txtmaHS.getText())){
            JOptionPane.showMessageDialog(rootPane, "Ma hoc sinh khong duoc de trong");
            ok= false;
        }
        else {
            maHS= txtmaHS.getText();
        }
         if("".equals(txtrenluyen.getText())){
            JOptionPane.showMessageDialog(rootPane, "Rèn luyện không được để trống");
            ok= false;
        }
        else {
            renluyen= txtrenluyen.getText();
        }
         if("".equals(txtkhenthuong.getText())){
            JOptionPane.showMessageDialog(rootPane, "Khen thuỏng không được để trống");
            ok= false;
        }
        else {
            khenthuong= txtkhenthuong.getText();
        }
         if("".equals(txttotnghiep.getText())){
            JOptionPane.showMessageDialog(rootPane, "Tốt nghiệp không được để trống");
            ok= false;
        }
        else {
            totnghiep= txttotnghiep.getText();
        }
         try {
            namhoc = Integer.parseInt(txtnamhoc.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Năm học không hợp lệ");
            ok = false;
        }
        if(ok){
            DoiTuong.HocKy h= new DoiTuong.HocKy(hocky,maHS,renluyen, khenthuong, totnghiep, namhoc);
            new HocKyCon().ThemMoi(h);
            JOptionPane.showMessageDialog(rootPane, "Thêm mới thành công");
            danhsach1.add(h);
            hienThiDanhSach("select* from hocky");
            XoaText();
        }
    }                                        

    private void tblDanhSachMouseClicked1(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        //click
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //sua
        String hocky=null, maHS= "", renluyen=null, khenthuong=null, totnghiep=null; 
        int namhoc=0;
        boolean ok= true;
        if("".equals(txthocky.getText())){
            JOptionPane.showMessageDialog(rootPane, "Hoc ky khong duoc de trong");
            ok= false;
        }
        else {
            hocky= txthocky.getText();
        }
        if("".equals(txtmaHS.getText())){
            JOptionPane.showMessageDialog(rootPane, "Ma hoc sinh khong duoc de trong");
            ok= false;
        }
        else {
            maHS= txtmaHS.getText();
        }
         if("".equals(txtrenluyen.getText())){
            JOptionPane.showMessageDialog(rootPane, "Rèn luyện không được để trống");
            ok= false;
        }
        else {
            renluyen= txtrenluyen.getText();
        }
         if("".equals(txtkhenthuong.getText())){
            JOptionPane.showMessageDialog(rootPane, "Khen thuỏng không được để trống");
            ok= false;
        }
        else {
            khenthuong= txtkhenthuong.getText();
        }
         if("".equals(txttotnghiep.getText())){
            JOptionPane.showMessageDialog(rootPane, "Tốt nghiệp không được để trống");
            ok= false;
        }
        else {
            totnghiep= txttotnghiep.getText();
        }
         try {
            namhoc = Integer.parseInt(txtnamhoc.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Năm học không hợp lệ");
            ok = false;
        }
        if(ok){
            DoiTuong.HocKy h= new DoiTuong.HocKy(hocky,maHS,renluyen, khenthuong, totnghiep, namhoc);
            new HocKyCon().CapNhat(h);
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
            int viTri= tblDanhSach.getSelectedRow();
            danhsach1.remove(viTri);
            danhsach1.add(h);
            hienThiDanhSach("select* from hocky");
            XoaText();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //xoá
        int viTri= tblDanhSach.getSelectedRow();
        DoiTuong.HocKy h = danhsach1.get(viTri);
        new HocKyCon().Xoa(h);
            JOptionPane.showMessageDialog(rootPane, "Xoa thanh cong");
            danhsach1.remove(viTri);
            hienThiDanhSach("select* from hocky");
            XoaText();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        // TODO add your handling code here:
        //click
        int viTri= tblDanhSach.getSelectedRow();
        DoiTuong.HocKy h = danhsach1.get(viTri);
        txthocky.setText(h.getHocky());
        txtmaHS.setText(h.getMaHS());
        txtrenluyen.setText(h.getRenluyen());
        txtkhenthuong.setText(h.getKhenthuong());
        txttotnghiep.setText(h.getTotnghiep());
        txtnamhoc.setText(""+h.getNamhoc());
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String taikhoan=lbtaikhoan.getText();
        String chucvu=lbchucvu.getText();
        if(chucvu.equals("chủ nhiệm")){
            new GiaoVienForm().setVisible(true);
            this.dispose();
         }else if(chucvu.equals("ad")){
           new Admin().setVisible(true);
        this.dispose();
         }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HocKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbchucvu;
    private javax.swing.JLabel lbtaikhoan;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txthocky;
    private javax.swing.JTextField txtkhenthuong;
    private javax.swing.JTextField txtmaHS;
    private javax.swing.JTextField txtnamhoc;
    private javax.swing.JTextField txtrenluyen;
    private javax.swing.JTextField txttotnghiep;
    // End of variables declaration//GEN-END:variables
}
